"""
Django settings for gallery project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
from decouple import config, Csv
from datetime import timedelta
#from contrib import utils

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PACKAGE_DIR = BASE_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

DJANGO_APP = config('DJANGO_APP')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

DOMAIN_LOCAL_SERVER = config("DOMAIN_LOCAL_SERVER")
DOMAIN_SERVER = config("DOMAIN_SERVER")

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
ALLOWED_HOSTS += [DOMAIN_LOCAL_SERVER, DOMAIN_SERVER, '*']

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())
CSRF_TRUSTED_ORIGINS += [f'https://{DOMAIN_LOCAL_SERVER}', f'https://{DOMAIN_SERVER}']

SECURE_CROSS_ORIGIN_OPENER_POLICY = None
#SECURE_SSL_REDIRECT = False

X_FRAME_OPTIONS = 'SAMEORIGIN'

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',
    #'django.contrib.sitemaps',
    'axes',
    'photologue',
    'sortedm2m',
    'gallery',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'axes.middleware.AxesMiddleware',
    'gallery.middleware.LoginRequiredMiddleware',
    'gallery.middleware.QuotasMiddleware',
]

ROOT_URLCONF = "gallery.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates', ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'gallery.context_processors.params',
            ],
        },
    },
]

WSGI_APPLICATION = "gallery.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASE_NAME = config('DATABASE_NAME')
DATABASE_USER = config('DATABASE_USER')
DATABASE_PASSWORD = config('DATABASE_PASSWORD')

SQLITE3=config('SQLITE3')
MARIADB=config('MARIADB')
POSTGRES=config('POSTGRES')

DATABASES = {
    SQLITE3: {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
        "OPTIONS": {
            "timeout": 20,
        },
    },
    MARIADB: {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS' : {
            "init_command": "SET foreign_key_checks = 0;SET sql_mode='STRICT_TRANS_TABLES';",
            },
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': config("DATABASE_MARIADB_HOST"),
        'PORT': config("DATABASE_MARIADB_PORT", cast=int),
    },
    POSTGRES: {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': config("DATABASE_POSTGRES_HOST"),
        'PORT': config("DATABASE_POSTGRES_PORT", cast=int),
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

#LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = 'fr-FR'

LANGUAGES = (
    ('fr', 'Français'),
    ('en', 'English'),
)

TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_L10N = True
USE_TZ = False

LOCALE_CODE = "fr_FR"
LOCALE_LC_ALL = "fr_FR.UTF-8"


LOCALE_PATHS = (
    BASE_DIR / 'photologue' / 'locale',

)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

## LOGGING
# CRITICAL=50, ERROR=40, WARN=30, INFO=20, DEBUG=10 and NOTSET=0
LOGGING_FILE = config('LOGGING_FILE')

if DEBUG:
    LOGGING_FILE = f'{DJANGO_APP}.log'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(asctime)s - %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_FILE,
            'maxBytes': 1024*1024*15, # 15MB
            'backupCount': 10,
            'formatter': 'simple',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        DJANGO_APP: {
            'handlers': ['file', ],
            'propagate': True,
            'level': 'INFO',
        },
         'axes': {
            'handlers': ['file', ],
            'propagate': True,
            'level': 'INFO',
        },
    },
}

# ACCOUNT
#
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = "/"

LOGIN_EXEMPT_URLS = (
    #r'^home/$',
)

##
# application
ADMINS = [
    (config('SUPERADMIN_MAIL'), config('SUPERADMIN'), config('SUPERADMIN_PASS'), True),
    (config('DEFAULT_USER_MAIL'), config('DEFAULT_USER'), config('DEFAULT_USER_PASS'), False),
]
MANAGERS = ADMINS

# django mail
#
DEFAULT_HTTP_PROTOCOL = config("DEFAULT_HTTP_PROTOCOL")
DEFAULT_TO_EMAIL = config("DEFAULT_TO_EMAIL")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
DEFAULT_EMAIL_CONTACT = config("DEFAULT_EMAIL_CONTACT")

EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int),
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)

## AXES
#

AXES_IPWARE_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR','REMOTE_ADDR', ]
AXES_LOCKOUT_PARAMETERS = ["ip_address", "user_agent"]
SILENCED_SYSTEM_CHECKS = ['axes.W003']
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_RESET_ON_SUCCESS=True

## PHOTOLOGUE
#
PHOTOLOGUE_GALLERY_SAMPLE_SIZE = 6
PHOTOLOGUE_DIR = 'photologue'

#DJANGORESIZED_DEFAULT_SIZE = [1920, 1080]
DJANGORESIZED_DEFAULT_SCALE = config("DEFAULT_SCALE", cast=float)
DJANGORESIZED_DEFAULT_QUALITY = config("DEFAULT_QUALITY", cast=int)
DJANGORESIZED_DEFAULT_KEEP_META = True
DJANGORESIZED_DEFAULT_FORCE_FORMAT = 'JPEG'
DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {'JPEG': ".jpg"}
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = False

# app
#
APP_TITLE = config("APP_TITLE")
APP_SUB_TITLE = config("APP_SUB_TITLE")
MEDIA_QUOTA = config("MEDIA_QUOTA", cast=float)

